version: '3.8'
services:
  app:
    build: .
    container_name: speedhorizon-app
    restart: always
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - RABBITMQ_URL=amqps://<USERNAME>:<PASSWORD>@gorilla.lmq.cloudamqp.com/tuyfyhrn
      - REDIS_URL=rediss://default:<PASSWORD>@redis-18249.c14.us-east-1-3.ec2.redns.redis-cloud.com:18249 