name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '18'
  FRONTEND_PORT: 3000
  BACKEND_PORT: 5001

jobs:
  # Test ve Build Job'u
  test-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Frontend Dependencies
      run: npm ci
      working-directory: ./
      
    - name: Install Backend Dependencies
      run: npm ci
      working-directory: ./src/api
      
    - name: Run Frontend Linting
      run: npm run lint
      working-directory: ./
      
    - name: Run Backend Linting
      run: npx eslint src/api/*.js
      working-directory: ./
      
    - name: Build Frontend
      run: npm run build
      working-directory: ./
      env:
        NEXT_PUBLIC_API_URL: https://speedhorizon.onrender.com
        
    - name: Test Backend API
      run: |
        cd src/api
        npm test
      env:
        MONGODB_URI: mongodb://kubra32nur:kubra32kubra@ac-w5zd64r-shard-00-00.ijfvnnc.mongodb.net:27017,ac-w5zd64r-shard-00-01.ijfvnnc.mongodb.net:27017,ac-w5zd64r-shard-00-02.ijfvnnc.mongodb.net:27017/?ssl=true&replicaSet=atlas-4y348o-shard-0&authSource=admin&retryWrites=true&w=majority&appName=speedhorizon
        PORT: ${{ env.BACKEND_PORT }}
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: .next/
        retention-days: 7

  # Frontend Deployment (Netlify)
  deploy-frontend:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Build Frontend
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: https://speedhorizon.onrender.com
        
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './out'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: nfp_uhTdwuEbytbbLHWGfwZj7Hm3RXHxt7vHd1b8
        NETLIFY_SITE_ID: dainty-sopapillas-63df79
      timeout-minutes: 1

  # Backend Deployment (Render)
  deploy-backend:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Backend Dependencies
      run: npm ci
      working-directory: ./src/api
      
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v1.0.0
      with:
        service-id: speedhorizon.online
        api-key: rnd_Q1vmITdhLMEMjEpojVo52SsIN9JX
        wait-for-success: true

  # Security Scan
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Security Audit
      run: npm audit --audit-level moderate
      working-directory: ./
      
    - name: Run Security Audit (Backend)
      run: npm audit --audit-level moderate
      working-directory: ./src/api

  # Performance Test
  performance-test:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Build Application
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: https://speedhorizon.onrender.com
        
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v10
      with:
        configPath: './lighthouserc.json'
        uploadArtifacts: true
        temporaryPublicStorage: true 